import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, writeFileSync, symlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Store } from '../lib/store.mjs';
import { SkillsService } from '../lib/skills.mjs';
import { startServer } from '../server.mjs';
const skill='---\nname: test-workflow\ndescription: A user-owned synthetic workflow\n---\nUse the supplied evidence, then answer plainly. Never run scripts.\n';
function setup(t){const dir=mkdtempSync(join(tmpdir(),'luheng-skills-'));const store=new Store(dir);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});return {dir,store,skills:new SkillsService(store)};}
test('fresh installation is generic, empty, API-first, without demo content',t=>{const {store}=setup(t);assert.equal(store.get('settings','main').mode,'api');assert.deepEqual(store.all('memories'),[]);assert.deepEqual(store.all('mail'),[]);assert.deepEqual(store.all('skills'),[]);assert.ok(store.get('agents','coordinator').permissions.includes('web.read'));});
test('immutable text package import, list, view and dedup have no execution side effect',t=>{const {dir,skills}=setup(t);const input={files:[{path:'SKILL.md',content:skill},{path:'references/note.txt',content:'synthetic data only'}]};const one=skills.importPackage(input),two=skills.importPackage(input);assert.equal(one.id,two.id);assert.equal(skills.list().length,1);assert.equal(skills.view(one.id).files.length,2);assert.match(skills.resolveSelection([one.id]).context,/test-workflow/);assert.equal(one.readOnly,true);assert.throws(()=>readFileSync(join(dir,'executed')));});
test('malformed metadata, binary, scripts, traversal, extra fields, sizes and selection are rejected',t=>{const {skills}=setup(t);for(const input of [{files:[]},{files:[{path:'../SKILL.md',content:skill}]},{files:[{path:'/SKILL.md',content:skill}]},{files:[{path:'SKILL.md',content:skill},{path:'scripts/run.sh',content:'touch anything'}]},{files:[{path:'SKILL.md',content:'no yaml'}]},{files:[{path:'SKILL.md',content:skill+'\0'}]},{files:[{path:'SKILL.md',content:skill+'a'.repeat(65536)}]},{files:[{path:'SKILL.md',content:skill,execute:true}]}])assert.throws(()=>skills.importPackage(input));const item=skills.importPackage({files:[{path:'SKILL.md',content:skill}]});assert.throws(()=>skills.resolveSelection([item.id,item.id]));assert.throws(()=>skills.resolveSelection(['../escape']));assert.throws(()=>skills.resolveSelection(new Array(5).fill(item.id)));});
test('tampered immutable bytes or symlinked bundle cannot be selected',t=>{const {dir,skills}=setup(t);const item=skills.importPackage({files:[{path:'SKILL.md',content:skill}]});const path=join(dir,'skills',item.id,'bundle.json');writeFileSync(path,'[]');assert.throws(()=>skills.view(item.id),/变更/);rmSync(path);symlinkSync('/etc/hosts',path);assert.throws(()=>skills.view(item.id),/不安全/);});
test('old seed migration archives only exact original provenance and retains all user edits and permissions',t=>{const dir=mkdtempSync(join(tmpdir(),'luheng-seed-'));let store=new Store(dir);const expected={id:'demo-rule',title:'演示材料处理原则',content:'本演示要求：工作材料标注来源，未经批准不提交OA、不发送邮件。检查台账后按完成情况、待办、风险、下一步四项整理。此规则是测试流程，不是单位真实规章。',source:'系统内置虚构流程 · DEMO-002',version:1,scope:'workspace',ownerAgentId:null,createdAt:new Date().toISOString()};store.put('memories',expected.id,expected);store.put('memories','demo-maintenance',{...expected,id:'demo-maintenance',content:'user-edited'});store.put('memories','my-record',{...expected,id:'my-record'});const actor={...store.get('agents','coordinator'),permissions:['knowledge.read'],personality:'my custom style'};store.put('agents',actor.id,actor);store.put('settings','main',{...store.get('settings','main'),mode:'demo'});store.db.prepare('DELETE FROM migrations WHERE version=5').run();store.close();store=new Store(dir);assert.equal(store.get('memories','demo-rule'),null);assert.deepEqual(store.get('seed_archive','memories:demo-rule').payload,expected);assert.equal(store.get('memories','demo-maintenance').content,'user-edited');assert.ok(store.get('memories','my-record'));assert.deepEqual(store.get('agents',actor.id),actor);assert.equal(store.get('settings','main').mode,'api');store.close();store=new Store(dir);assert.equal(store.all('seed_archive').length,1);store.close();rmSync(dir,{recursive:true,force:true});});
test('HTTP Skills require local session and read-only selections reach model without new permissions',async t=>{const dir=mkdtempSync(join(tmpdir(),'luheng-skill-http-'));const messages=[];const app=await startServer({port:0,dataDir:dir,stepDelay:1,completion:async request=>{messages.push(request.messages);return {message:{role:'assistant',content:'Synthetic completion only'},usage:null};}});t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});const r=await fetch(app.url+'/'),cookie=r.headers.get('set-cookie').split(';')[0];const request=(path,body)=>fetch(app.url+path,{method:body?'POST':'GET',headers:{cookie,origin:app.url,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await fetch(app.url+'/api/skills')).status,401);const imported=await(await request('/api/skills/import',{files:[{path:'SKILL.md',content:skill}]})).json();assert.ok(imported.id);const before=app.store.get('agents','coordinator').permissions;const created=await(await request('/api/tasks',{prompt:'First synthetic question',skillIds:[imported.id],submissionId:'synthetic-id-skills-0001'})).json();for(let n=0;n<200&&app.engine.liveTask(created.id).status!=='completed';n++)await new Promise(r=>setTimeout(r,10));const first=app.engine.liveTask(created.id);assert.equal(first.status,'completed',first.error);assert.ok(messages[0].some(message=>message.role==='system'&&message.content.includes('test-workflow')));assert.deepEqual(app.store.get('agents','coordinator').permissions,before);assert.equal(app.store.get('tasks',first.id).skillContext,undefined);const next=await(await request('/api/tasks',{prompt:'Second synthetic question',previousTaskId:first.id,skillIds:[imported.id]})).json();for(let n=0;n<200&&app.engine.liveTask(next.id).status!=='completed';n++)await new Promise(r=>setTimeout(r,10));assert.ok(messages[1].some(message=>message.role==='user'&&message.content==='First synthetic question'));assert.ok(messages[1].some(message=>message.role==='assistant'&&message.content==='Synthetic completion only'));assert.equal((await request('/api/tasks',{prompt:'Wrong role',agentId:'researcher',previousTaskId:first.id})).status,400);});

test('HTTP text packages larger than the old 100KB limit import without broadening other request limits',async t=>{const dir=mkdtempSync(join(tmpdir(),'luheng-skill-large-'));const app=await startServer({port:0,dataDir:dir});t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});const cookie=(await fetch(app.url+'/')).headers.get('set-cookie').split(';')[0];const headers={cookie,origin:app.url,'content-type':'application/json'};const files=[{path:'SKILL.md',content:skill},...Array.from({length:3},(_,i)=>({path:`references/${i}.txt`,content:'界'.repeat(16000)}))];const response=await fetch(app.url+'/api/skills/import',{method:'POST',headers,body:JSON.stringify({files})});assert.equal(response.status,201,await response.text());const unrelated=await fetch(app.url+'/api/tasks',{method:'POST',headers,body:JSON.stringify({prompt:'x'.repeat(110000)})});assert.equal(unrelated.status,400);});
test('orphaned identical immutable bytes safely retry while corrupt dedup never looks successful',t=>{const {store,skills}=setup(t);const input={files:[{path:'SKILL.md',content:skill}]};const item=skills.importPackage(input);store.delete('skills',item.id);assert.equal(skills.importPackage(input).id,item.id);const path=join(skills.root,item.id,'bundle.json');writeFileSync(path,'[]');assert.throws(()=>skills.importPackage(input),/变更/);});
test('archived original records can be explicitly restored, with no overwrite or workflow reactivation',async t=>{const dir=mkdtempSync(join(tmpdir(),'luheng-archive-restore-'));const app=await startServer({port:0,dataDir:dir});t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});const payload={id:'old-synthetic',title:'Old synthetic note',content:'Unmodified test note',source:'test-only'};app.store.put('seed_archive','memories:old-synthetic',{id:'memories:old-synthetic',kind:'memories',originalId:payload.id,payload,migration:5});const cookie=(await fetch(app.url+'/')).headers.get('set-cookie').split(';')[0];const request=()=>fetch(app.url+'/api/seed-archive/restore',{method:'POST',headers:{cookie,origin:app.url,'content-type':'application/json'},body:JSON.stringify({id:'memories:old-synthetic'})});assert.equal((await request()).status,200);assert.deepEqual(app.store.get('memories',payload.id),payload);assert.equal(app.store.get('settings','main').mode,'api');assert.equal((await request()).status,400);assert.deepEqual(app.store.get('memories',payload.id),payload);});
