import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store } from '../lib/store.mjs';
import { LocalAccessService, FULL_ACCESS_CONFIRMATION } from '../lib/local-access.mjs';
function fixture(t) { const root=fs.mkdtempSync(path.join(os.tmpdir(),'luheng-local-')); const files=path.join(root,'files'), outside=path.join(root,'outside');fs.mkdirSync(files);fs.mkdirSync(outside);const store=new Store(path.join(root,'data'));const service=new LocalAccessService(store,{getSecrets:()=>['unit-test-application-secret']});t.after(async()=>{await service.close();store.close();fs.rmSync(root,{recursive:true,force:true});});return {root,files,outside,store,service}; }
const enable=(s,f,m='confirm')=>s.configure({mode:m,roots:[f],allFiles:false,onboardingComplete:true});
const command=(f,code,extra={})=>({kind:'command',executable:process.execPath,args:['-e',code],cwd:f,...extra});
const write=(f,content='fictional report')=>({kind:'write',path:path.join(f,'report.txt'),content});
test('default disabled, read-only, traversal and credential paths',async t=>{const {service:s,files:f,outside:o,store}=fixture(t);fs.writeFileSync(path.join(f,'r.txt'),'fictional');await assert.rejects(s.propose({kind:'read',path:path.join(f,'r.txt')}),/尚未连接/);enable(s,f,'read_only');assert.equal((await s.propose({kind:'read',path:path.join(f,'r.txt')})).result.content,'fictional');await assert.rejects(s.propose(write(f)),/只读/);await assert.rejects(s.propose(command(f,'console.log(1)')),/只读/);fs.writeFileSync(path.join(o,'r.txt'),'other');await assert.rejects(s.propose({kind:'read',path:path.join(f,'..','outside','r.txt')}),/超出/);for(const filename of ['.env','.npmrc','.git-credentials']){fs.writeFileSync(path.join(f,filename),'fake');await assert.rejects(s.propose({kind:'read',path:path.join(f,filename)}),/敏感凭据/);}await assert.rejects(s.propose({kind:'read',path:path.join(store.dir,'agent.sqlite')}),/内部数据库/);assert.throws(()=>enable(s,path.parse(f).root),/整盘/);});
test('write approval is exact one-use and returned snapshots cannot tamper it',async t=>{const {service:s,files:f}=fixture(t);enable(s,f);const p=await s.propose(write(f));assert.equal(fs.existsSync(p.operation.snapshot.path),false);p.operation.snapshot.content='tampered';s.state().pending[0].snapshot.path=path.join(f,'wrong.txt');const results=await Promise.allSettled([s.approve(p.operation.id),s.approve(p.operation.id)]);assert.deepEqual(results.map(r=>r.status),['fulfilled','rejected']);assert.equal(fs.readFileSync(path.join(f,'report.txt'),'utf8'),'fictional report');assert.equal(fs.existsSync(path.join(f,'wrong.txt')),false);});
test('full access challenge is scope revision and expiry bound; restart downgrades',async t=>{const {service:s,files:f,outside:o,store}=fixture(t);enable(s,f);assert.throws(()=>s.configure({mode:'full',roots:[f],allFiles:false}),/二次确认/);const scope={roots:[f],allFiles:false};let c=s.requestFullAccess(scope);assert.throws(()=>s.configure({mode:'full',roots:[o],allFiles:false,challenge:c.challenge,confirmation:FULL_ACCESS_CONFIRMATION}),/二次确认/);enable(s,f,'read_only');assert.throws(()=>s.configure({mode:'full',...scope,challenge:c.challenge,confirmation:FULL_ACCESS_CONFIRMATION}),/二次确认/);c=s.requestFullAccess(scope);s.challenges.get(c.challenge).expiresAt=Date.now()-1;assert.throws(()=>s.configure({mode:'full',...scope,challenge:c.challenge,confirmation:FULL_ACCESS_CONFIRMATION}),/二次确认/);c=s.requestFullAccess(scope);s.configure({mode:'full',...scope,challenge:c.challenge,confirmation:FULL_ACCESS_CONFIRMATION});assert.equal((await s.propose(write(f))).operation.status,'completed');await s.close();const next=new LocalAccessService(store);assert.equal(next.state().mode,'confirm');assert.equal(next.state().allFiles,false);await next.close();});
test('pending rejected after revoke downgrade scope change and task cancel',async t=>{const {service:s,files:f,outside:o}=fixture(t);for(const change of [()=>s.revoke(),()=>enable(s,f,'read_only'),()=>enable(s,o),()=>s.cancelTask('fake-task')]){enable(s,f);const p=await s.propose(write(f),{taskId:'fake-task'});change();await assert.rejects(s.approve(p.operation.id),/失效|已处理/);assert.equal(fs.existsSync(path.join(f,'report.txt')),false);}});
test('actual harmless command and write data absent from metadata/SQLite logs',async t=>{const {service:s,files:f,store}=fixture(t);enable(s,f);const p=await s.propose(command(f,'console.log("synthetic-command-output");console.log(process.env.LUHENG_TEST_SECRET||"no-secret")'));const r=await s.approve(p.operation.id);assert.equal(r.result.exitCode,0);assert.match(r.result.stdout,/synthetic-command-output\nno-secret/);assert.equal(r.result.executionBoundary,'host_process_no_os_sandbox');assert.equal(JSON.stringify(store.all('local_operations')).includes('synthetic-command-output'),false);const w=await s.propose(write(f,'synthetic-body-no-log'));assert.equal(JSON.stringify(store.all('local_operations')).includes('synthetic-body-no-log'),false);s.reject(w.operation.id);});
test('timeout output cap and revocation stop real processes',async t=>{const {service:s,files:f}=fixture(t);enable(s,f);let p=await s.propose(command(f,'setInterval(()=>{},1000)',{timeoutMs:120}));await assert.rejects(s.approve(p.operation.id),/时限/);p=await s.propose(command(f,'process.stdout.write("x".repeat(80000));setInterval(()=>{},1000)'));await assert.rejects(s.approve(p.operation.id),/64KiB/);p=await s.propose(command(f,'setInterval(()=>{},1000)'));const run=s.approve(p.operation.id);setTimeout(()=>s.revoke(),60);await assert.rejects(run,/撤销|取消/);assert.equal(s.state().operations.find(o=>o.id===p.operation.id).status,'invalidated');assert.equal(s.running.size,0);});
test('approval flags relative executable and secrets rejected',async t=>{const {service:s,files:f}=fixture(t);enable(s,f);await assert.rejects(s.propose({...command(f,'console.log(1)'),userApproval:true}),/未获允许/);await assert.rejects(s.propose({...command(f,'console.log(1)'),executable:'node'}),/绝对路径/);await assert.rejects(s.propose(command(f,'console.log("unit-test-application-secret")')),/内存凭据/);await assert.rejects(s.propose(write(f,'unit-test-application-secret')),/内存凭据/);});
test('oversize and binary reads bounded',async t=>{const {service:s,files:f}=fixture(t);enable(s,f,'read_only');fs.writeFileSync(path.join(f,'large.txt'),'x'.repeat(300000));await assert.rejects(s.propose({kind:'read',path:path.join(f,'large.txt')}),/256KiB/);fs.writeFileSync(path.join(f,'binary.txt'),Buffer.from([0,1,2]));await assert.rejects(s.propose({kind:'read',path:path.join(f,'binary.txt')}),/纯文本/);});

test('Windows path algorithm rejects devices UNC ADS reserved names and normalizes trailing slash',async()=>{const {validateLocalAbsolutePath}=await import('../lib/local-access.mjs');assert.equal(validateLocalAbsolutePath('C:\\Work\\reports\\',path.win32,'win32'),'C:\\Work\\reports');for(const p of ['C:relative','\\\\server\\share','\\\\?\\C:\\work','C:\\Work\\report.txt:secret','C:\\Work\\NUL.txt','C:\\Work\\trailing.','C:\\Work\\trailing '])assert.throws(()=>validateLocalAbsolutePath(p,path.win32,'win32'),/绝对路径|Windows路径/);assert.equal(validateLocalAbsolutePath('/tmp/folder\\',path.posix,'linux'),'/tmp/folder\\');});
