import assert from 'node:assert/strict';
import test from 'node:test';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {startServer} from '../server.mjs';
const project=fileURLToPath(new URL('..',import.meta.url));

test('Local permission UI state machine and exact approval markup',async()=>{
const base=await mkdtemp(join(tmpdir(),'local-access-dom-qa-')),roots=join(base,'selected');await mkdir(roots);let app;
const proof=process.env.LOCAL_ACCESS_UI_EVIDENCE_DIR||join(base,'evidence');await mkdir(proof,{recursive:true});
const nodes=new Map(),actions=[],report=[];
function node(id){if(!nodes.has(id))nodes.set(id,{id,value:'',textContent:'',innerHTML:'',disabled:false,hidden:false,checked:false,dataset:{},style:{},focus(){},setAttribute(){},querySelector(){return null;},querySelectorAll(){return[];},closest(){return null;}});return nodes.get(id);}
class FakeFormData{constructor(form){this.values=form.values||{};}get(k){return this.values[k]??null;}getAll(k){const v=this.values[k];return Array.isArray(v)?v:v===undefined?[]:[v];}has(k){return this.values[k]!==undefined&&this.values[k]!==false;}}
function form(id,values){return {id,values,connected:true,getAttribute(){return id;},querySelector(selector){return selector==='[type="submit"]'?node(id+'-submit'):selector==='.modal-error'?node(id+'-error'):null;}};}
const log=(name)=>{report.push(name);console.log('PASS '+name);};
try{
 app=await startServer({port:0,dataDir:join(base,'app-data'),stepDelay:5});
 const env={console,URL,AbortController,Date,Intl,Map,Set,Array,JSON,Number,String,Boolean,RegExp,Error,Promise,FormData:FakeFormData,crypto:globalThis.crypto,setTimeout:()=>0,clearTimeout(){},setInterval(){},navigator:{platform:'Linux',clipboard:{writeText:async()=>{}}},sessionStorage:{getItem(){return null;},setItem(){},removeItem(){}},location:{hash:''},window:{addEventListener(){},scrollTo(){}},document:{body:{style:{},classList:{remove(){},toggle(){}}},activeElement:null,querySelector(selector){return nodes.get(selector)||nodes.get(selector.replace(/^#/,''))||null;},querySelectorAll(){return[];},addEventListener(){},contains(el){return el?.connected!==false;}}};
 for(const id of ['main','modal-root','toast-root','local-roots','local-all-files','local-save-button','local-access-toggle','local-access-menu','local-tools-summary','local-all-files-field'])node(id);
 const boot=await fetch(app.url);const cookie=boot.headers.get('set-cookie')?.split(';')[0]||'';let pickerResponse={cancelled:true,paths:[]};env.fetch=async(path,opts={})=>{if(path==='/api/local-access/select-folders')return new Response(JSON.stringify(pickerResponse),{status:200,headers:{'Content-Type':'application/json'}});return fetch(app.url+path,{...opts,headers:{...opts.headers,cookie,origin:app.url}});};
 const context=vm.createContext(env);const code=(await readFile(project+'/public/app.js','utf8')).replace('renderChrome();loadState();setInterval(()=>loadState(),2000);','');vm.runInContext(code,context);context.productionOpenModal=vm.runInContext('openModal',context);
 // Use the same live context, with test-only rendering replaced after evaluating production handlers.
 context.qaActions=actions;vm.runInContext(`renderChrome=()=>{};render=()=>{};toast=(message,error=false)=>{qaActions.push({toast:message,error});};openModal=(kind,id)=>{modal={kind,id};qaActions.push({modal:kind,id});};closeModal=()=>{if(modal?.kind==='local-full-confirm')localAccessChallenge=null;modal=null;};navigate=next=>{view=next;};loadState=async()=>{const data=await api('/api/state');state={...state,...data};await syncLocalAccess(data.localAccess);online=true;loaded=true;};`,context);
 const run=(s)=>vm.runInContext(s,context);const state=()=>app.localAccess.state();
 await run('loadState()');run("productionOpenModal('agent','coordinator')");let editor=node('modal-root').innerHTML;let checked=[...editor.matchAll(/name="permissions" value="([^"]+)"[^>]*checked/g)].map(m=>m[1]);assert.equal(checked.length,12);assert.deepEqual([...checked].sort(),[...app.store.get('agents','coordinator').permissions].sort());run("productionOpenModal('agent')");editor=node('modal-root').innerHTML;checked=[...editor.matchAll(/name="permissions" value="([^"]+)"[^>]*checked/g)].map(m=>m[1]);assert.deepEqual(checked.sort(),['knowledge.read','workspace.write']);run('closeModal()');log('production role editor retains all 12 coordinator permissions; new roles keep only two safe defaults');run('maybeLocalOnboarding()');assert.equal(actions.at(-1).modal,'local-access');assert.equal(state().mode,'disabled');run('closeModal();maybeLocalOnboarding()');assert.equal(run('modal'),null);assert.equal(state().configured,false);log('onboarding opens disabled and interruption does not grant or immediately reopen');
 await run("localAccessAction('local-defer',null)");assert.equal(state().configured,true);assert.equal(state().mode,'disabled');log('defer persists onboarding completion while access remains disabled');
 context.qaForm=form('local-access-form',{localMode:'confirm',roots});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');assert.equal(state().mode,'confirm');assert.deepEqual(state().roots,[roots]);assert.equal(node('local-access-form-error').textContent,'');const selector=run('renderLocalAccessSelector()');assert.match(selector,/role="menuitemradio" aria-checked="true" data-action="local-mode" data-mode="confirm"/);assert.equal((selector.match(/role="menuitemradio"/g)||[]).length,4);assert.match(selector,/完全访问权限/);log('composer renders four explicit modes with exactly one selected state');
 context.qaForm=form('local-operation-form',{kind:'write',path:join(roots,'exact.txt'),content:'EXACT-TEST-WRITE\n<script>fake</script>'});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');assert.equal(state().pending.length,1);let markup=run('renderLocalConversation()');assert.match(markup,/EXACT-TEST-WRITE/);assert.match(markup,/&lt;script&gt;fake&lt;\/script&gt;/);assert.doesNotMatch(markup,/<script>fake/);assert.match(markup,/批准这一次/);assert.match(markup,/完整替换文件内容/);await writeFile(join(proof,'write-approval-markup.html'),markup);log('write approval renders complete escaped exact content and target');
 let op=state().pending[0];context.qaControl={dataset:{id:op.id},disabled:false,closest(){return null;}};await run("localAccessAction('local-approve',qaControl)");assert.equal(state().pending.length,0);assert.equal(await readFile(join(roots,'exact.txt'),'utf8'),'EXACT-TEST-WRITE\n<script>fake</script>');assert.equal(state().operations[0].status,'completed');log('real-server exact digest approval writes once and is consumed');
 context.qaForm=form('local-operation-form',{kind:'write',path:join(roots,'reject.txt'),content:'UNAPPROVED'});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');context.qaControl={dataset:{id:state().pending[0].id},disabled:false,closest(){return null;}};await run("localAccessAction('local-reject',qaControl)");assert.equal(state().operations[0].status,'rejected');await assert.rejects(readFile(join(roots,'reject.txt'),'utf8'));log('reject performs no file write');
 context.qaForm=form('local-operation-form',{kind:'command',executable:process.execPath,args:JSON.stringify(['-e','process.stdout.write("EXACT-COMMAND-OUTPUT\\n")']),cwd:roots});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');assert.equal(state().pending.length,1);markup=run('renderLocalConversation()');assert.ok(markup.includes(process.execPath));assert.match(markup,/EXACT-COMMAND-OUTPUT/);assert.match(markup,/15 秒/);assert.match(markup,/未按所选目录隔离/);await writeFile(join(proof,'command-approval-markup.html'),markup);context.qaControl={dataset:{id:state().pending[0].id},disabled:false,closest(){return null;}};await run("localAccessAction('local-approve',qaControl)");assert.equal(state().operations[0].status,'completed');assert.match(run('renderLocalConversation()'),/EXACT-COMMAND-OUTPUT/);log('command exact executable argv cwd timeout approval executes and displays escaped output');
 context.qaForm=form('local-operation-form',{kind:'write',path:join(roots,'stale.txt'),content:'STALE'});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');const unchangedRevision=state().revision;context.qaControl={dataset:{mode:'confirm'},disabled:false};await run("localAccessAction('local-mode',qaControl)");assert.equal(state().revision,unchangedRevision);assert.equal(state().pending.length,1);log('selecting the active mode is a no-op and preserves pending exact approvals');context.qaControl={dataset:{mode:'read_only'},disabled:false};await run("localAccessAction('local-mode',qaControl)");assert.equal(state().mode,'read_only');assert.equal(state().pending.length,0);assert.equal(state().operations[0].status,'invalidated');assert.match(run('renderLocalConversation()'),/审批已失效/);log('downgrade immediately invalidates pending actions and renders honest status');
 context.qaForm=form('local-access-form',{localMode:'full',roots});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');assert.equal(state().mode,'read_only');assert.equal(run('modal.kind'),'local-full-confirm');assert.match(run('renderLocalFullConfirmation()'),/riskUnderstood/);run('closeModal()');assert.equal(state().mode,'read_only');assert.equal(run('localAccessChallenge'),null);log('full-access first stage does not grant; dismiss clears ephemeral challenge');
 context.qaForm=form('local-access-form',{localMode:'full',roots});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');context.qaForm=form('local-full-confirm-form',{riskUnderstood:true});await run('handleLocalForm(qaForm)');assert.equal(state().mode,'full');assert.equal(state().allFiles,false);assert.deepEqual(state().roots,[roots]);assert.match(run('renderLocalAccessSelector()'),/local-access-pill full/);log('full access requires second explicit consent and remains selected-roots scope');
 context.qaForm=form('local-access-form',{localMode:'confirm',roots:'relative/path'});run("modal={kind:'local-access'}");await run('handleLocalForm(qaForm)');assert.match(node('local-access-form-error').textContent,/绝对目录路径/);assert.equal(state().mode,'full');log('relative scope is rejected before backend request');
 node('local-roots').value=roots;context.qaControl={dataset:{},disabled:false};pickerResponse={cancelled:true,paths:[]};await run("localAccessAction('local-pick-folders',qaControl)");assert.equal(node('local-roots').value,roots);assert.equal(state().mode,'full');pickerResponse={cancelled:false,paths:[roots,join(base,'additional')]};await run("localAccessAction('local-pick-folders',qaControl)");assert.equal(node('local-roots').value,roots+'\n'+join(base,'additional'));assert.equal(state().mode,'full');assert.deepEqual(state().roots,[roots]);log('picker cancellation preserves draft; choices merge without granting or widening policy');
 context.qaForm=form('local-operation-form',{kind:'command',executable:process.execPath,args:JSON.stringify(['-e','setTimeout(()=>process.stdout.write("SHOULD-BE-STOPPED"),3000)']),cwd:roots});run("modal={kind:'local-access'}");const runningManual=run('handleLocalForm(qaForm)');const runningDeadline=Date.now()+5000;while(!state().operations.some(o=>o.kind==='command'&&o.status==='executing')){if(Date.now()>runningDeadline)throw new Error('manual command did not enter executing state');await new Promise(resolve=>setTimeout(resolve,10));}assert.equal(run('localManualBusy'),true);assert.equal(run('localAccessBusy'),false);context.qaControl={dataset:{mode:'disabled'},disabled:false};await run("localAccessAction('local-mode',qaControl)");await runningManual;assert.equal(state().mode,'disabled');assert.equal(state().pending.length,0);assert.match(run('renderLocalSettingsSummary()'),/本机访问已关闭/);log('revoke remains available while a full-mode manual command is running, stops it, and reflects closed mode');
 assert.equal(actions.filter(a=>a.error).length,0);await writeFile(join(proof,'dom-qa-result.json'),JSON.stringify({passed:true,checks:report,visualQA:'Not run: isolated Chromium blocked by Unix socket sandbox; separate cloud browser blocked loopback URL',backend:'real isolated server; temporary app database, file roots and harmless Node stdout command'},null,2));
}finally{await app?.close();await rm(base,{recursive:true,force:true});}
});
