import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile(new URL('./generic-chat-ui.mjs',import.meta.url),'utf8');
const predicate=source.match(/function submittedTaskCompleted\(id\)\{[^}]*\}/)?.[0];
assert.ok(predicate);
test('UI completion gate waits for the newly accepted task, not the previous completed turn',()=>{
 const tasks=new Map([['old',{status:'completed'}],['new',{status:'queued'}]]);
 const c=vm.createContext({chatTaskId:'old',submitting:true,pollBusy:false,taskById:id=>tasks.get(id)});
 vm.runInContext(predicate,c);
 assert.equal(vm.runInContext("submittedTaskCompleted('new')",c),false);
 c.chatTaskId='new';c.submitting=false;
 assert.equal(vm.runInContext("submittedTaskCompleted('new')",c),false);
 tasks.get('new').status='completed';c.submitting=true;
 assert.equal(vm.runInContext("submittedTaskCompleted('new')",c),false);
 c.submitting=false;c.pollBusy=true;
 assert.equal(vm.runInContext("submittedTaskCompleted('new')",c),false);
 c.pollBusy=false;
 assert.equal(vm.runInContext("submittedTaskCompleted('new')",c),true);
});
